07-24 15:47:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "TULLY" не найден
Column "TULLY" not found; SQL statement:
select * from users where user_name=tully [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:880)
	at org.h2.command.Parser.prepareCommand(Parser.java:247)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execQuery(Executor.java:27)
	at dbService.dao.UsersDAO.getUserId(UsersDAO.java:25)
	at dbService.DBService.addUser(DBService.java:28)
	at main.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
02-02 01:23:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "BAY" не найдена
Table "BAY" not found; SQL statement:
select * from bay where id=1 [42102-187]
02-02 01:27:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAY_NAME" не найден
Column "BAY_NAME" not found; SQL statement:
insert into users (bay_name, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:29:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAY_NAME" не найден
Column "BAY_NAME" not found; SQL statement:
insert into users (bay_name, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:31:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAY_NAME" не найден
Column "BAY_NAME" not found; SQL statement:
insert into users (bay_name, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:38:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into users (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:39:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into users (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:40:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into users (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:42:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into users (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:42:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into users (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:42:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into bay (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:43:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into bay (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:46:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into bay (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 01:47:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO BAY ('bayName'[*], 'amount') VALUES ('название покупки', '10 шт') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO BAY ('bayName'[*], 'amount') VALUES ('название покупки', '10 шт') "; expected "identifier"; SQL statement:
insert into bay ('bayName', 'amount') values ('название покупки', '10 шт') [42001-187]
02-02 01:59:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "BAYNAME" не найден
Column "BAYNAME" not found; SQL statement:
insert into bay (bayName, amount) values ('название покупки', '10 шт') [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:856)
	at org.h2.command.Parser.parseColumnList(Parser.java:840)
	at org.h2.command.Parser.parseInsert(Parser.java:1040)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:305)
	at org.h2.command.Parser.parse(Parser.java:277)
	at org.h2.command.Parser.prepareCommand(Parser.java:242)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at dbService.executor.Executor.execUpdate(Executor.java:18)
	at dbService.dao.BayListDAO.insertBayList(BayListDAO.java:33)
	at dbService.BayListDBService.addBayList(BayListDBService.java:32)
	at main.Main.main(Main.java:16)
02-02 02:01:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "BAY" уже существует
Table "BAY" already exists; SQL statement:
create table bay (id bigint auto_increment, bayName varchar(256), amount varchar(256), primary key (id)) [42101-187]
02-02 02:44:32 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Столбец "NAME" не найден
Column "NAME" not found [42122-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at dbService.dao.BayListDAO.lambda$getBayList$2(BayListDAO.java:39)
	at dbService.dao.BayListDAO$$Lambda$3/145362.handle(Unknown Source)
	at dbService.executor.Executor.execQuery(Executor.java:26)
	at dbService.dao.BayListDAO.getBayList(BayListDAO.java:35)
	at dbService.BayListDBService.getBayList(BayListDBService.java:29)
	at main.Main.main(Main.java:24)
02-02 15:29:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Таблица "BAY" не найдена
Table "BAY" not found; SQL statement:
select * from bay [42102-187]
02-02 15:45:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-187]
02-02 15:46:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-187]
02-02 15:47:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "BAY" не найдена
Table "BAY" not found; SQL statement:
select * from bay where id=0 [42102-187]
02-04 00:15:51 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.samvel.jetty.dbService.BayListDBService.getH2Connection(BayListDBService.java:89)
	at ru.samvel.jetty.dbService.BayListDBService.<init>(BayListDBService.java:17)
	at ru.samvel.jetty.Main.main(Main.java:24)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 21 more
02-04 00:34:43 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.panic(MVStore.java:368)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:351)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2782)
	at org.h2.mvstore.db.MVTableEngine$Store.<init>(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:98)
	at org.h2.engine.Database.getPageStore(Database.java:2389)
	at org.h2.engine.Database.open(Database.java:669)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
	at org.h2.engine.Engine.openSession(Engine.java:167)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:145)
	at org.h2.engine.Engine.createSession(Engine.java:128)
	at org.h2.engine.Engine.createSession(Engine.java:26)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:347)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:108)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.samvel.jetty.dbService.BayListDBService.getH2Connection(BayListDBService.java:89)
	at ru.samvel.jetty.dbService.BayListDBService.<init>(BayListDBService.java:17)
	at ru.samvel.jetty.Main.main(Main.java:33)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]" [50000-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:H:/MyProjects/simple-web-server/h2db.mv.db [1.4.187/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:337)
	... 21 more
